### ISSUE TITLE
I can see simpler management views (contents/history etc) without header/footer/search)

### ISSUE THREAD

**Issue by MAX-786** [collective/volto-hydra#10]
## Description

As an editor, I want to see simpler management views (contents/history etc) without header/footer/search), so that I can manage pages at one place.

## Technical Approach

Hopefully we can use the `@plone/client` to fetch this list and relevant content to show on this page.

**Comment by djay** [comment]
@MAX-786 this is just about removing header and footer from all admin UI pages that take up the center of the screen.
e.g. contents, history, edit, sharing, control panel, etc. Also the edit view for items that don't have blocks editor.
All of these pages should a breadcrumbs, a title but no other top level nav, top level search, footer or other parts of the page that are more frontend/theme related

**Comment by MAX-786** [comment]
> All of these pages should a breadcrumbs, a title but no other top level nav, top level search, footer or other parts of the page that are more frontend/theme related

Simply put we are left with toolbar and a breadcrumbs, and atmost a sidebar if it is in edit view.
