### ISSUE TITLE
I can Change the text of a selected text block from sidepanel after clicking on it, save and see updated page

### ISSUE THREAD

**Issue by MAX-786** [collective/volto-hydra#16]
# Problem

We need to be able to edit fields on blocks that don't currently make them visible, like text on a text block.
- [ ] List of all the fields on blocks that don't appear on their schema

# Technical

Does this mean we need to override all blocks that don't make visible all their schemas? Is there any easier way?

**Comment by djay** [comment]
@JeffersonBledsoe to see if it's hard or not to get the richtext field to appear in the schema. If it is hard we can just delay this until later.

**Comment by JeffersonBledsoe** [comment]
As noted in Discord:

> If you open the file `/packages/volto-slate/src/blocks/Text/schema.js`, add `value` into the `fields` key within the fieldset definition and add the following object into `properties`, you get full slate in the sidebar to test with:
> 
> ```
> value: {
>     title: 'Body',
>     widget: 'slate',
> },
> ```

**Comment by djay** [comment]
@MAX-786 if its easy it would be nice to put the markdown help into it's own section or move to bottom or somehow hide it. or can split that out for later

**Comment by MAX-786** [comment]
@djay We can move the markdown help to bottom by shadowing the `DefaultTextBlockEditor`. I'll do it in the same PR as above.
