### ISSUE TITLE
I can Click on a block in preview to see its configuration appear in sidepanel

### ISSUE THREAD

**Issue by MAX-786** [collective/volto-hydra#23]
- [x] don't select two blocks if one block is inside another
- [ ] Try to make the listening to the click events as robust as possible so the integrator can't accidentally prevent it from happening
- [x] don't require the integrator to do anything other than add the block ids to the blocks

**Comment by djay** [comment]
@MAX-786 as disussed should be able to do it by adding data attributes without having to call an extra api

**Comment by djay** [comment]
@MAX-786 there is one problem with this one. If you are on the order tab it won't switch to the block settings if you click on a new block in preview

**Comment by MAX-786** [comment]
Thanks for pointing it out!
Let me see if the fix is complicated or just some single redux action dispatch.
I'll do it accordingly.

**Comment by MAX-786** [comment]
Its an easy fix i'll create a new PR and merge it right away
