### ISSUE TITLE
I can Format text on a text block using formatting on quanta toolbar (e.g. bold)

### ISSUE THREAD

**Issue by MAX-786** [collective/volto-hydra#32]
- there are paragraph formats (e.g. heading) and char formats (e..g bold). We can split out the paragraph formatting into a seperate card if it makes sense.
- The quanta toolbar has a different layout from slate. We can follow quanta or slate layout. If it's just as easy to follow quanta then follow that.
   - quanta groups all paragraph styles into a single dropdown. and keeps char styles as seperate buttons.

Tasks
- [x] Select adn turn something bold
- [x] select same text and unbold it
- [x] click bold and start typing bold
- [x] untoggle bold and now typing is not bold
- [x] add in italic and other styles

Edge cases
- [ ] select bold + normal text and then click bold
- [ ] select bold and italic next to each other and click bold
- [ ] ...

**Comment by djay** [comment]
Interesting. seems like some formatting is built into contenteditable like cmd-b and adding a new bullet.
Which means somehow that needs to be translated back into nodes. But slate must have the same issue.


![Image](https://github.com/user-attachments/assets/eef16a05-ad8e-4fd0-aba6-d2deeb90043c)

**Comment by djay** [comment]
@MAX-786 I think the extra code you are looking for on how it's done now is in https://6.docs.plone.org/volto/configuration/volto-slate/api.html. There is a whole plugin system that later will need to be supported perhaps.
The default styles are in https://github.com/plone/volto/tree/main/packages/volto-slate/src/editor/plugins/StyleMenu
I haven't looking if there is anyway to use this code without changing the definition of a slate plugin but I guess not?

**Comment by djay** [comment]
@MAX-786 the code you want for the transforms is in https://github.com/ianstormtaylor/slate/blob/2c9d5ec87fddf447794a563356bfd729235888a4/docs/api/transforms.md?plain=1
I suspect this you can use in hyrda.js. Still not sure thats the right place to do it though
