### ISSUE TITLE
As an integrator I can not have to load hydra.js all the time to know user has started editing

### ISSUE THREAD

**Issue by djay** [collective/volto-hydra#47]
This means anon browsing is kept lean by not loading things they don't have to 

- [ ] use a url argument to signify the frontend can load hydra.js and init the bridge
- [ ] simplify the readme and explain once how to init the bridge and use the token

**Comment by djay** [comment]
@MAX-786 I think it would be good to do this now since the current README is very hard to understand. it says how to init three times and its much harder to understand that you get the token after you init rather than before.

**Comment by djay** [comment]
Currently auth is broken. so switching to this should fix that problem

**Comment by JeffersonBledsoe** [comment]
@MAX-786 Just a heads up, the query parameter should be named 'access_token' as it follows the auth pattern defined in https://www.rfc-editor.org/rfc/rfc6750#section-2.3 . No direct benefit to us as we aren't using the token directly for requesting resources in the admin UI, but it makes things clearer for the integrator.

**Comment by MAX-786** [comment]
Ooh I used as 'auth_token' same as it is stored in cookies... good thing I havent pushed that commit in remote :)
I will change it now.
