### ISSUE TITLE
I should see as much of the frontend as possible when editing esp on mobile (get rid of extra header)

### ISSUE THREAD

**Issue by djay** [collective/volto-hydra#56]
# Problem

There are things about volto currently that make it hard to edit on mobile. But in general the volto and quanta UI is designed to be minimal so to make the UI works on mobile also. We should not get in the way of this by adding more things to the UI

# Proposed solution

## no additional toolbar or breadcrumbs

While it is nice having both the breadcrumbs and the frontend url on screen, in reality the frontend will most likely have it's own breadcrumbs so it's just wasting space. You can also ways use contents or the browser url bar to help see where you are. So I think going back to the quanta design of the frontend taking up 100% of the same and no new bar is better.

- [x] #62
- [x] #89
   <img width="469" alt="image" src="https://github.com/collective/volto-hydra/assets/41700/c782f8a2-6f5e-4715-b48e-db281a8b45fa">

- [ ] We should get rid of all the borders so iframe takes up the full center space
   <img width="1438" alt="image" src="https://github.com/collective/volto-hydra/assets/41700/98ed2814-da59-4f7d-a74d-6e8141e235b5">

- [ ] remove the breadcrumbs
- [x] put in breadcrumbs and basic subnav into demo frontend

## Quanta toolbar
Other issues around being able to add and delete blocks on mobile should largely be solved by the quanta toolbar. 
But need to ensure this toolbar goes on the bottom on mobile during edit, and the quantatoolbar goes to the top

1 | 2 | 3
-|-|-
![image](https://github.com/collective/volto-hydra/assets/41700/9e371f1b-1073-4a17-9450-b915dc6c5018) | ![image](https://github.com/collective/volto-hydra/assets/41700/0c3350f1-c1a1-4cdc-9efc-e7ef6ba2e720 ) | ![image](https://github.com/collective/volto-hydra/assets/41700/774a50d9-48af-4cf8-9995-1b00442433b9)

**Comment by MAX-786** [comment]
> I think we can put the ability to change the frontend in the persoanl preferences menu

this may not be our first requirement to do so but for now I think we can make it collapse-able, like at the top and have an arrow to expand it again.

**Comment by MAX-786** [comment]
> We should get rid of all the borders so iframe takes up the full center space

It is the same width as the Form.jsx of the Volto, meaning volto have this too, so are we okay with changing it? bcz then it would be very cluttering. I can give it a try and see how it looks.

**Comment by djay** [comment]
You aren't comparing the same things. Form is just dealing with how volto renders content. A frontend is fully responible for rendering the whole page. If we want the IFrame to appear invisible and editing experience to be like volto then we need there to be nothing added to this middle section I think.

**Comment by MAX-786** [comment]
>  put in breadcrumbs and basic subnav into demo frontend

Done by https://github.com/MAX-786/hydra-nextjs-frontend/pull/2

**Comment by MAX-786** [comment]
Closed by #90
