### ISSUE TITLE
URL input bar usability issues

### ISSUE THREAD

**Issue by JeffersonBledsoe** [collective/volto-hydra#59]
The input bar and button above the IFrame window, shown below, has a number of usability issues with it:
<img width="458" alt="" src="https://github.com/collective/volto-hydra/assets/30210785/e737007a-2d26-40eb-afc3-1b587652c546">

- You can't press 'enter' on the 

## Suggested solution

should be all solved by #57 and moving to standard select component. Doesn't really need to track the current url anymore

## Other solutions considered

from jeff

- Split the bar into it's own component that accepts an `onSubmit` to better encapsulate logic and tidy up `View.jsx`
- Add a label to the input (add an ID to the input, then use `for="my-input-id"`
- Wrap the input and button in a form and move the `onClick` of the button to `onSubmit` on the form.
  - This handles things like pressing enter when the input is focused to submit the form
- Use an uncontrolled input. No need to keep React state around to change the input value when the browser does this for us so simplifies the code.

**Comment by djay** [comment]
@JeffersonBledsoe see #57. We get rid of the input and move it into the personal tools menu.

**Comment by MAX-786** [comment]
Closed by #90
