### ISSUE TITLE
I can Select which frontend to view the current page

### ISSUE THREAD

**Issue by MAX-786** [collective/volto-hydra#7]
## Description

As an editor, I want to Select which frontend to view the current page by providing a URL so that I can preview/manage multiple frontends at one place (adminUI).

## Technical Approach

Once the user (editor) is authenticated we can ask for an URL which will then try connecting with frontend using Bridge ( simply by using iframe for now).  We will enter the view URL into the edit URL on the login page and save it somewhere in the browser (e.g. session storage)
- Need to display the iFrame with the page in it

In the final version config can be used to specify the frontend urls to use

# followup tasks
- [ ] #44

**Comment by djay** [comment]
@MAX-786 maybe it can be split out but I think this should also remember using a cookie what the last url you used was and also have a  default that comes from an env variable

**Comment by djay** [comment]
@MAX-786 can we also move up the url box into the top bar witht he breadcrumbs so we get almost all of hte screen filled with the iframe?



![Image](https://github.com/collective/volto-hydra/assets/41700/7e1c6ef5-a86f-4619-b656-b0083a30b6fa)

**Comment by MAX-786** [comment]
> @MAX-786 maybe it can be split out but I think this should also remember using a cookie what the last url you used was and also have a default that comes from an env variable

Okay, so when you login, the default url will be loaded as per env and once editor change the url , it will be saved in cookie ( but just the origin of url )

**Comment by MAX-786** [comment]
> @MAX-786 can we also move up the url box into the top bar witht he breadcrumbs so we get almost all of hte screen filled with the iframe?

It can be, but the thing is, input field is in the same component as [iframe,](https://github.com/collective/volto-hydra/blob/fc1873ddf1366aaea608de62b6f276ced8aa9967/packages/volto-hydra/src/components/Iframe/View.jsx#L53C1-L59C11) so currently the value is controlled by useState but if we move it in Breadcrumb component then IG we have to use prop drilling or redux store perhaps, I'll look into it and try it out first.
