### ISSUE TITLE
as an integrator I can specify which blocks can be added

### ISSUE THREAD

**Issue by djay** [collective/volto-hydra#70]
Pass this on iframe init.
Means the for the demo we won't get confused adding blocks that aren't supported
api should allow for extension later to support rules about which can be added inside containers, changes to schemas on blocks (options not supported etc), custom block schemas etc

**Comment by djay** [comment]
@MAX-786 I moved this one up because it will make it less confusing to demo if you can't add blocks you can't see

**Comment by MAX-786** [comment]
@djay Currently I just restricted the block types to : text & image

Later, we can work through the rules about adding blocks inside containers and etc.
