### ISSUE TITLE
I can click on an external url and it will not load inside the iframe

### ISSUE THREAD

**Issue by djay** [collective/volto-hydra#94]
maybe as new tab?
but should mimic the behaviour of normal volto

**Comment by djay** [comment]
@MAX-786  its a worse bug than I thought.

if you click on the hydra.pretagov.com url in the frontpage you get 



![Image](https://github.com/collective/volto-hydra/assets/41700/6313794b-436b-4769-abac-11f02c52af6f)

and it seems to remember it because a reload gets the same thing

**Comment by MAX-786** [comment]
One fix as discussed, is that telling integrator to hook into the `onRouteChange(path)` which will tell adminUI where to navigate, and all the other links in the frontend will do no change in adminUI and links will be opened as usual (its upto frontend if it wants to open in new tab or in the same tab ie iframe).

So something like this needs to be done by integrator if they want the routing in adminUI via iframe:
```js
    <HoverableDropdown
      item={item}
      subItems={subItems}
      onClick={() => {
        bridge.onRouteChange(extractEndpoints(item["@id"])); // extractEndpoints(item["@id"]) -> pathname
      }}
    />
```

**Comment by djay** [comment]
If the user clicks on an external link inside the IFrame then hydra already
knows about it. There is no extra hooks needed. Just exit out of the editor
and replace it with the url that was clicked
